ARDUINO_DIR  = /usr/share/arduino-1.6.5
TARGET       = node
ARDUINO_LIBS = OneWire_master GSM Sensirion
ARDUINO_HWLIBS = EEPROM SoftwareSerial

#BOARD_TAG    = uno
BOARD_TAG    = nano
#BOARD_TAG    = mini
ARDUINO_PORT = /dev/ttyUSB2

include /usr/share/arduino-1.6.5/Arduino.mk
